/**
 * Colour maps, as GLSL.
 *
 * The polynomial coefficients are NOT written out here. They are imported from
 * colormaps.ts and formatted into the shader source at module load, so the GPU
 * and the test suite evaluate literally the same numbers. Duplicating ninety
 * floats into a shader string would guarantee they drift apart eventually.
 *
 * Why these colormaps are perceptually uniform, and why that matters here, is
 * documented in colormaps.ts. The short version: colour is carrying quantitative
 * information (probability density), so the map must not invent brightness
 * structure that is absent from the data. A rainbow map does exactly that.
 *
 * Both are original work generated by tools/generate-colormaps.mjs, which keeps
 * the licensing of this repository unambiguous.
 */

import { DEPTH_COEFFICIENTS, EMBER_COEFFICIENTS } from '../colormaps';

/** Format coefficients as a GLSL vec3 array literal. */
function toGlslArray(
  coefficients: ReadonlyArray<readonly [number, number, number]>,
): string {
  const entries = coefficients
    .map(([r, g, b]) => `    vec3(${r.toExponential(9)}, ${g.toExponential(9)}, ${b.toExponential(9)})`)
    .join(',\n');
  return `vec3[${coefficients.length}](\n${entries}\n  )`;
}

const DEGREE_PLUS_ONE = DEPTH_COEFFICIENTS.length;

export const PALETTES_GLSL = /* glsl */ `
const vec3 DEPTH_C[${DEGREE_PLUS_ONE}] = ${toGlslArray(DEPTH_COEFFICIENTS)};
const vec3 EMBER_C[${DEGREE_PLUS_ONE}] = ${toGlslArray(EMBER_COEFFICIENTS)};

// Horner evaluation on the CENTRED domain u = 2t - 1. The fit was produced on
// [-1,1] because a monomial fit on [0,1] is ill-conditioned; evaluating on the
// wrong domain would produce garbage rather than a subtly worse ramp.
vec3 evaluateColormap(vec3 coefficients[${DEGREE_PLUS_ONE}], float t) {
  float u = 2.0 * clamp(t, 0.0, 1.0) - 1.0;
  vec3 acc = coefficients[${DEGREE_PLUS_ONE - 1}];
  for (int i = ${DEGREE_PLUS_ONE - 2}; i >= 0; i--) {
    acc = acc * u + coefficients[i];
  }
  return clamp(acc, 0.0, 1.0);
}

vec3 paletteDepth(float t) { return evaluateColormap(DEPTH_C, t); }
vec3 paletteEmber(float t) { return evaluateColormap(EMBER_C, t); }

// A cool-to-hot electron glow: deep blue core through cyan to white.
// Hand-designed rather than perceptually uniform, and offered as the default
// because it reads as luminous emission rather than as a data ramp.
vec3 paletteGlow(float t) {
  vec3 a = vec3(0.02, 0.06, 0.25);
  vec3 b = vec3(0.10, 0.45, 0.95);
  vec3 c = vec3(0.45, 0.90, 1.00);
  vec3 d = vec3(1.00, 1.00, 1.00);
  if (t < 0.33) return mix(a, b, t / 0.33);
  if (t < 0.70) return mix(b, c, (t - 0.33) / 0.37);
  return mix(c, d, (t - 0.70) / 0.30);
}

vec3 palette(int which, float t) {
  t = clamp(t, 0.0, 1.0);
  vec3 c;
  if (which == 0) c = paletteGlow(t);
  else if (which == 1) c = paletteDepth(t);
  else c = paletteEmber(t);
  // Guard against a polynomial undershooting slightly at the ends, which would
  // read as a muddy off-colour where the data is actually zero.
  return max(c, vec3(0.0));
}

// Phase colouring: two opposing hues for the two signs of psi.
// Amber for positive, teal for negative. Deliberately not red/green.
vec3 phaseColour(float signedValue, float magnitude) {
  vec3 positive = vec3(1.00, 0.62, 0.24);
  vec3 negative = vec3(0.24, 0.78, 0.85);
  return mix(negative, positive, step(0.0, signedValue)) * magnitude;
}
`;
